apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
  labels:
    name: wordpress
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-limit
  namespace: wordpress
spec:
  hard:
    pods: "30"
