---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-sync-operator
  namespace: kube-system
imagePullSecrets:
  - name: github-andromedarabbit
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-sync-operator
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - configmaps
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - namespaces
      - pods
    verbs:
      - get
  - apiGroups:
      - extensions
      - apps
    resources:
      - replicasets
      - deployments
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - create
      - update
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: secret-sync-operator
subjects:
  - kind: ServiceAccount
    name: secret-sync-operator
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: secret-sync-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-sync-operator
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      name: secret-sync-operator
  template:
    metadata:
      labels:
        name: secret-sync-operator
    spec:
      serviceAccountName: secret-sync-operator
      containers:
        - name: secret-sync-operator
          image: docker.pkg.github.com/unchartedsky/dockers/secret-sync-operator:latest
          command:
            - secret-sync-operator
          imagePullPolicy: IfNotPresent
          env:
            - name: WATCH_NAMESPACE
              value: ""
            - name: OPERATOR_NAME
              value: "secret-sync-operator"
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
