apiVersion: v1
kind: Namespace
metadata:
  name: wordpress
  labels:
    name: wordpress
---
apiVersion: v1
kind: LimitRange
metadata:
  name: resource-limit-range
  namespace: wordpress
spec:
  limits:
  - default:
      cpu: 1
      memory: 512Mi
    defaultRequest:
      cpu: 0.1
      memory: 100Mi
    type: Container
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-limit
  namespace: wordpress
spec:
  hard:
    pods: "30"
