# Source: wordpress/templates/tests/test-mariadb-connection.yaml
apiVersion: v1
kind: Pod
metadata:
  name: "credentials-test"
  namespace: plaintext
  annotations:
    "helm.sh/hook": test-success
spec:
  containers:
  - name: credentials-test
    image: docker.io/bitnami/wordpress:5.3.0-debian-9-r0
    imagePullPolicy: "IfNotPresent"
    env:
      - name: MARIADB_HOST
        value: mariadb
      - name: MARIADB_PORT
        value: "3306"
      - name: WORDPRESS_DATABASE_NAME
        value: "bitnami_wordpress"
      - name: WORDPRESS_DATABASE_USER
        value: "bn_wordpress"
      - name: WORDPRESS_DATABASE_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mariadb
            key: mariadb-password
    command: ["sh", "-c", "mysql --host=$MARIADB_HOST --port=$MARIADB_PORT --user=$WORDPRESS_DATABASE_USER --password=$WORDPRESS_DATABASE_PASSWORD"]
  restartPolicy: Never
