apiVersion: ENC[AES256_GCM,data:80M=,iv:IGp8+XRF/xgjXs8ZuvqHZDM0GXct54BKyRAWK5lhUGg=,tag:098qzb6s7oCvFn1ARuIoQg==,type:str]
clusters:
-   cluster:
        certificate-authority-data: ENC[AES256_GCM,data:pVQQ0rU1M8DbJ30xdCq7OHorV+CyiHhB6lUQJGfVkCIaqFMX3f7Q55xtAaHwHtq4Ex7E4nm+3m9itS3YJaaxuE/qlWDo4uqER9Hbm3g5JHzrUjG11vg7cXgNcmuPMedkNlq0dRdEBvIRTm4nbbo5NURkNU/7vY487axeyKEA0iQkvEFLaaMpCM1XPtELmbrdPS9JEHE8wgepxSYnZ8dOejzHaogzRxzquXxSG/FR+5bAOSiL0D1cmmnqZZcvLb6sjoV4+e+LQAen7Kxv6A03fMuijbiKpGgfYowvZG8wrdl0nBiea74xYX3FLTSRyHSgEsaC0gBW44pq0o5Q1/M24ni3nl0EhN7/xSID6p3QsNbklB9Ku23fuYYONvcOXyeub659LXvpqSJEPbZwsFUzmqRnG/gJ2xsQcgG3XdbUQ8y1uK/+53sj9d4MhYE8l0rwcp7OUVdiLa1L142PBVUPJQNhUzNtFV/cUmBHre/Uiu+Z+yuBiSw5ztjE2fP20Y5zUIPnbb3sXsrSLN+AQ/iClk8JETiamlSZABnbu8EL/I+BCgEUqsUoYqAKIN5grocgBMy0yJXZy+oNzndwCP4HKUFftSXnrIlU2piGmB9VcPSt5wQEY5BbKxlPpP6iJaLFXDgSLRtAR826oJdI9x3fZoIXjc7ROSg4iPOvxSmzghKwBh/H1WV5IeeB466SXBS2OHlHjAKtuW3YJwNRzxx5f3R7ZBkg+iowB4H8e+BD96IfJMZF3NdRy5WxFcpyxJLfcYZgLGHTl/ptomIR9PodtfmU3ItH9hjsElsHUYsAKSAWQMfKuE0qAYAJNl3/i/cuRFu/66LtGMWoKTog+gmFNWkJVtxRTzG/MCBVgz0L/i8mPuJ+wjyMzqfKdbNw85Lb7dVhuR3KoDNdNM5rT1U20/buLdhQkKO4aVHyiCkioV4cf3ujsbfsZucG4Ju2JY97f94MwGw79qYh2jTJbH/DoigSjCJnYujBZTn2SFspIm63PB3X1VPWxvLQEozhmCTmn6yBIGWeXWZQls8kklF+pF0cvOaZg76Hu5yJzTib8YJLTJelyNatwFl1zM3XurudByjWVvbFZNOIBs2aq64Y59/i/TIiU2oWah1WaJtsEM9o8RJDOhsqjx1GIgDdccJvvcFL7yO9vaqx7029D2E8PjHWulSfQchON5Y1RdpOa70ddBCA41JpK51PJKFIXTpx2PFgGKuRDNCxKcZGeNJadKHQmGca50K5pxOMILVg7guK9C8y3cqIQziGmUBmdTsFrNJAl9/wbOILqhlvE6p8cO+pYpalQas6xpDF2JeC2ZsKdyjbyn8JfZDYAf4MhpnwWV6SdidbGICp7aLrnSgwaMltfmjESHojHvbElXExnguVQUyz3MGNfOspnNRJJloXXDgwM6EGcZaC5hH+/mQU44WewrHjsUvP8lGi+LJIUPUo7Qm5fP3exFseOZM6p5AxXE1gjxNgJVfD1TVgfO6YlV8QFupYhIou/AFRHd/NnUPFmFUFdvQLjJxyjyaSwwb3sXzMr469w6NaM1FRkmXf+py71PQ8TlVkfgou+xpDBF07xsvoHahZXmJB2bHjN7pjOxHCFDNExFhsvFYb9h4hbpRUgAkboZks4jlDz8h8lc0lCRQnoNIEVaDvVebBNVrjBuAyse8yA9i+9xnSyfceRG0rYZ7c5c4fN6LVZMFZdKd5qyvLXlLm/3sw0Y2a3r/+ZvESwJ+Oc/fALazeSOg4PeLmrvVO1d8eClwkgLOx2UAVfj3OIeG1BEHX+0RsLOFsI4NaNqS+0j3C5vFfCPcIoH13r9O6xunYKUrSoXQdX1lcfso4E0r3sMGuk0ueQFaHkCQRkCRIN9dMw1YZTJJeA6tY6dYUlWUD+Q+OxitI6+L08DpilbR+D/3Z5+0Mjk0TYbzO0lgTzo59MfxskSKc55n/Bn0e2qbNcAE1x1piQFfOhFf5Muq1losve09bHPn8Blyjyrn9A2TFDKd1VJNBLDY3UEyibLp9P0qoE++J+r7tKg3GMdEG3a7E6yDntrEDAnViNw==,iv:HIGm9BjzQsd8WY3GgxquEhyTk2qKPPJLk4Ue0oMSxzU=,tag:1vnmJVYjkCHhSfFHH861Ag==,type:str]
        server: ENC[AES256_GCM,data:s1Y+dWk/3akU8NnFlOlY07LNiXUEnv6v+a/QDRD4h1PXNoI8kAjRaYMSyF8HkS29acIpwyvEnf9EKzPWbXM2eeBdKw==,iv:XRMLGcz/c8vgM6O2xdMnlYbfSi2zJXdRQHR88jHLbJc=,tag:HhHgGySRkkd1d2ntXm22GA==,type:str]
    name: ENC[AES256_GCM,data:dW6DMYVffwTMSaFsuw==,iv:ZsCrRCOyW5iljL8oTrlOsYiNsCY7AuLeUtGMAOwaB20=,tag:T07q/GsmQyl/JFVbjnJfPQ==,type:str]
contexts:
-   context:
        cluster: ENC[AES256_GCM,data:GcIHzBOqg0CS1qK+Uw==,iv:4mMF3TDHtp8N5FvywQllsBEOElXicM2lOTavl2CAfXg=,tag:8CQgmdex6T2tbvjcaoDOkg==,type:str]
        namespace: ENC[AES256_GCM,data:xqd/PGXhiDUW,iv:gcqKccbYjnZGUFVXtLUt2gj4g2Pjdip1rhj72GfA5YY=,tag:NVyiYy24lc+iNvYrnbsqXg==,type:str]
        user: ENC[AES256_GCM,data:tF54YxtLDoWKtvmFc9j0sFryxw==,iv:tzDa/SBRpYlL1HdEzwqwF+CAf9WIXmB5/nrgX10PlaM=,tag:JEfTSsCrj11rMzKK0Hx7UA==,type:str]
    name: ENC[AES256_GCM,data:J8CfyGl3eDrerFDKOQ==,iv:tta2OUF3amuC+MGgsrGZrVhO9jNTQVpT+sg6D1x8C2c=,tag:wuIflfrICfTnSi9i7FL2IA==,type:str]
current-context: ENC[AES256_GCM,data:/7547+Z62+rIPDFGXw==,iv:U4cWXG2X1kZe/mhwbgTEfu0DRNnDrmyAilM0HG4pcoc=,tag:HutnnC+7sKT1xi7LKtzRfw==,type:str]
kind: ENC[AES256_GCM,data:LyjjeSFS,iv:PFOCYNC4l5qH3+1n2EGYrc8LvDBJd4HfpKoOm7nbkr8=,tag:3Vod8rTQORpMVhBVKToumg==,type:str]
preferences: {}
users:
-   name: ENC[AES256_GCM,data:l3dFJzxN/iU0H9sqIXg2nOQiDQ==,iv:2KMB7YcnUiy7b9Z/nPtKM6MksGYPTZkWM6znm96KEOk=,tag:v/Re6Y2nWALssBVshl9aKQ==,type:str]
    user:
        token: ENC[AES256_GCM,data:HazIQ0knZF0h/4OU9Lm25EoIKPhKem1lqCZJjP2GjIQgwGIukFajs4Y4RZSO0Oyvb9igXxmWuY6KGbKFACN0JA==,iv:H368WWv7ZerCUm2dtYCCScQq/0Yh3PyRMK9Sq4G28XY=,tag:xCBGYWK2/58I+lEgVLh6Mw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-01-12T16:08:11Z'
    mac: ENC[AES256_GCM,data:KXXqqjoh4b3L8SBtGHSvaiioYAyFRlFjfT5hSS6tzSiTywhiDsR6E5BR461rK1RY5rGrYxBFJvp2zplDJJutxEdHOqURazVM/nQPPbRJX0kkygI+WCuEtxWFnMUZYiKulq9nl9TI3af0/ff/RkYNPteD48X/vzWzQZ4szGbokK4=,iv:sHxnq+NBqR82YIyPfGgo1mkIG1ZJ+4QdlSaChXJvyqU=,tag:H0mQO9W4QLhfaVfkopvezA==,type:str]
    pgp:
    -   created_at: '2020-01-12T16:08:09Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6yRV+ftA5XNARAAmWaV7VmK046tDH0hEbK8FsB3Ato4PV9FQ5mgttXEFfE4
            jXmqiuqW7oqbZBfpy23PHTUVnxGa+uAtD17Zj7Iouoa8h2oWZU/cVui9rhPM2+yU
            WlPBp0hUUQPLdN3W+S8KnJ2dJ9RGmX7Zdagu+um4FwN/PbB7xO4UUzphMWKbkkVg
            Tf8MzL0Oa5idO90RaPJXyHM6oANsNFO+wDIaBTJ/0nAwW/TnFg7Xe63tUdCG/5Bj
            G7Dq5oVqLYC06X2tOxz6jXNKKj+p6kBP5zsnYSFYXBArN186L2Cqfzk2nav+s3wT
            yx3Sobuw/awCTdSwfLjYwYI326hBOchHzYUJgDq6FpoCF91x3CXGmDGqa3EgPHSk
            t4CsW48FhSOonmf6vof+nrDfpfUTXkRi6k0KfK0GSHn1CSBAn0kFXJMc0pDFvtrm
            gFiNFz7KY/VTEYukyN8cSupKSRlUvDAEBXFfrdxgp5Pu5UT0C+pSImT6oF23OBSj
            cfmRLLxbjWKvlMmz32heeMRMqTk0mnzAmXL+i7J+xl61mOFWfTfZUnC+5USRAijA
            thfXi1vjHYbk72haaEaIN2oiDxoVg2LAOPlMan/579SgjJiRdAjQqUeFy/9/RefM
            Uer+/hJ07ttedJWh61Dwd1Mbd1mOJo+LaMPid2olqVXNP/Lxfa8Q8YVHLuH5IWvS
            XAENBkTrvpMR3nnvGkyEtsziGlmdEnTo4R40ws2MylWLwYKBf438CeMYGuFOHIUb
            nIngPd34MM7GCpKfPgqDH7wOphQ7Ej/2XCNl5O7miIqfR/ChTQS29vBTxF84
            =FrtF
            -----END PGP MESSAGE-----
        fp: fea55c7794732f67c619951fd178ef6721556cb9
    -   created_at: '2020-01-12T16:08:09Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyiIzYC95gBGARAAqZFnZdGCT3NBTt6MOV/GgZzWO1Q31/cyvLeizFInwd+M
            VULb0bH8W7fp0dcenF+Yj73VALQOFSP/Uf98Kga8gJRUmdI7S6j2QAV6UGhzlKqd
            HMkAcQqbKiEFdR4VzGB8daanzrUrxvDKTr7c0SpW3C7er5VEG9mJGZPy/n4gGt2b
            f+sce0rpBhs5E86ceqfYjU9qgL5YbKlV4DtwWVIZXMZ6DYTMhlFKKEhgfzFAFyVq
            wt0R1UtbAyCNXnxb2DeBezYkv3vAqEovqFp+37t+jw+2DFz4uVfytSkezPulgJsZ
            PG6r+DQqrohbZhbnOUIBtQv5qvbT3MTvtnMB5w2/cgVmCT+Dx0pZCtMO6znxavnH
            uamm972BvVHTpqhbeqMBAuRglwZo+wNZhKVP1f5jQAEp/L1sflicNIn+6/IHkMa3
            09FfSLqx1M7Wf0rodN6Ao71HdV8UzxzX2FeNeuG/8pMxKn4bcw7M26TV/iHSUnI0
            PC7zGkJQpoxwPZoRKS/kdF4oqgLFgG7qcdXd8h9yq8RRxU9WXOcKeDpzGn5xhr5O
            diIwyeTdUWcC+tVIZAUzgEUDQk8wvxsOHQ483HyEJGTTYKudVtwWolbPxZNR+84S
            yti9i1ipHMHWQWzsovsAx3rxng6dgQvZzSq+5/HmKEv6FQCWJ4wGgdK3fHWxkE7S
            UQGcb/9OSFl7M/sGmZ+4XpxLWCk0sbpZCZau9CVkMgDj3tR/Pnxn1ygeIJBYhcw9
            aC62NguMSuk+xCSl11/K+S7iCtk2Kf5JbDKdQNBDhjuvvg==
            =bUbk
            -----END PGP MESSAGE-----
        fp: BE13F9D526F84552FA528A09D56ADE51E65A1512
    -   created_at: '2020-01-12T16:08:09Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7WWstCwV13VARAAmngie0o1TGLl1jXyTrBE43/L6twrZsL+tmaMCR3RTGxq
            pyZAeuc5hnJZ60RJaEG10J1uAHaoLpQrOFtDx+JUYjLWsoAUrbq3s19H9ITK0brx
            x3cer1LVQVm5k3R7xVQ9Ye2Qj+aDx/tNB1xIaQ1pmvLcllYM6MesvuW4NzO9/BU9
            3FrU5EnpEvJCjtVRNnwHNgtQnViIzZV3BrMhei5anOIfezHwa6/8Oykl+WjwRj4j
            sAzaKa4NThTqwF2XoP+FOuRiD8b4ccIMfU5F3F8kCm0m2203DoEtehk03614DNGi
            BJ9vAwdSIefhaCWlzct6d+SZAJeMtt9zsMHWA3RIX3U3qSb1DQZVT3X4hHB+olRR
            RspTjTQ1I+N4xbShwQ/VqQp4FEyxKMEMgKMcZ2vkxbKATrdzvfDppKamYTQuDMgw
            1Ws9omOzbtfO5FT9CWQX29Q9VeMceoUnWV48kKmrCF3FyGZJwZCwigftGr/MGSxg
            uWLGHu1NIzdBwoHwnqBI/iDRKzSpMBdx+q46t3swCEbeTCLTTyFUE/BKB82b0/qc
            aMT8QAkXnpeD5EqDA6s3/A5wa1+dJZ/WmCBYAoqoSJxlfTyWVlW3oENdPbp4jFGE
            2LHKIcKXpL29j9pqUke3v+edIVH/kTLhbugWgDTrgeD3MRdqiT1wIX6yPkiMdAfS
            UQEYp38ydO+YOcBCCwozsPrbM/AJavfApAr1OOSNDbeNwEtkDszR9CHvqCqU2h/H
            K1qAdvOg3pm8XWVEIk/srt1kbte1+VSjFD/8fKbGBoF9DQ==
            =Seb6
            -----END PGP MESSAGE-----
        fp: AA337512457420FF9A6298D924BAFA429D76E5E1
    unencrypted_suffix: _unencrypted
    version: 3.5.0
