apiVersion: ENC[AES256_GCM,data:VOA=,iv:xVnzZ7Sfy4diNN2/nI7R6sR5AncD0vKalgmbOcHJTpE=,tag:/TTTARILG4W9wydPEdpfYQ==,type:str]
clusters:
-   cluster:
        certificate-authority-data: ENC[AES256_GCM,data:ULAhuQmPitfrkZYp/891fN9rbvwKpDOcS+amxdRuK7gfVaTC/wVV1B3GrejsSgKH0XY40vOxLCFUANQ3Z28IkvAM4oWnw3E/Mk+Ibt55Zj8n9zMcumpn7I4mVRQcFm9w5Id/TE8r+XdJfgNjbc26Twcyups6Ig4XYcPffdxOjguUVxgduhuUHGIjkEKdDHE3QimWp2l1qPfJcyAv4nOY6sd/KYVgV3VfOu9eP7asz8X04cRxJBF7dzK7kljD3cKc/Ja1j2W9tjbF/kDv0vEaURsqGT80CVtB1+fIA5TFY6QpQ3z6Ul7lMh0Mk8UP0CtSXaLnwVbTW63FmGyFiYjZJNW21zIGqnoD2vxhn1OF8lftxo4wjBnJ6mxIMN4qZU3l2LERVhWOD9MsFTvAVZOFQ0qqH3w0ewgeSQ5XSCfZJVb83Ijjn+zMrL2j8aQX+TpVjix6cRD0PCcIhOxAEgGp2sn2SyUXtdFnLK+Gcj1658NXw8hJVdN3aYiCmC1ZwHU0sVu8R/3vLxMzxB7Dj8e3rRn6YLH6qAvUtwJEQsNGydb4i1IN8F2HCKhfKTmB5jiN6TILP630aDB4bHJHzXZqQO93yK6FeQpP59T3IkLXeXra5oypHGlEj+qeZNQswAXMutp6NTmyzyBwZOTGPh1b3OklTm7dFdQnh6BVaeqiTYxMi9Ws4rKhPBcbDcsotEAYfLDS4vtPFZfRG3foFy8bTj8+28D7MTCblFUw3g0oiPM1tcA5j+iDHKWFDCV6JMaOWym+JjIkoQB+L8IOXkXDEp3MMm2cTsCQ0dRU+tmZK9bcUF0NZnYhH1OOOhgrSdSPwg/458j9oKH3mA1x23yewGAKPOS9V2J+xxqHOKra40gUP19q1wtkdt4AJW7PektSDJuCkbxvrHffYLXWUz8SQ7d6SVoxpoKZvueZjsqlwKI9Xb6U1NAVQKn61t/7vgbBkarcu/jXOyd1LITniGl39xFOFuV1L6BCLKBRx1yz6g4852LteUANFDn6fAstViSbJTKVHGn4Z0c2isd92SW6u1DG0ReBWQEW6Y4ZfCrIJgI6NZTZ02aP09IL1ZYMZriitNc9Oboj3dHuFoUeC2o6Xi6I/LRwTRP1ehDmpIxKXsHHBhlVMH1GQ0G+JEAhO0nDerAEQi3IjXZiYXxcQZGACfoQTqpKNMxt5LMnhApCSgA7IJ3LXr31zOQMRmVPnU3MfjSPp30OwCLfOooMk9IeqihCVxZwpYCf0uLxrun3y+dKiJWgzBPEwXJB3HeSIb6Aqjpt4OSC9wm4Ttcnd7BW+yaU8nLZAeU6eOjIs1qDOIz4MUhZPOBwU8fnmeSPFKq1giFV0yjXrSdS3qWNQ81zXzn22uKyOPdjqYwcVRm9x/mQn1Lmon1XRgdiCJfhJIZjG4xaHimjUAqvcVhElmzeprCBpjg3V9BItuDADnKaVQVf1fJUlftlYAijlkLeedimdpOsfZimL1bih4BYUvWUKYhSvyAKIhHief31GzeqPpy8pIybG6nM6a6yHiLaacUn2CT8tVUM1Uf6k+vvuCyExGraS7cbMojtkPfnvd71hchXB2kPiW4p2Yv6ZcYjUBa9V4Jq0KRLtKPpSOeDgyw3sVwLmLq4rVPClMsNd2LK3rs7OHaeKI2THwkHEznml/WqMm7rSWxiAnSiNsvKkeMbHsLPXynC0KIM2I8GBVtmWOr7oiNOPNFxAouKfaE5/2+tUknNVTctSTr3HuzfihO/ABsoBHDLBNdRok4WKmW/GFQZjr2ywO7TZuYV6hjjQ7EmDheHx1qccqYbntvOl8AanjNgct0KORA4tlYvfeeR38OcdPmmrdW/zyFHM6AZECEnoAvut9hpsvRcm8MQgAPKRrkWSQL+Mij8+gb+6ktgUv01de7Q1XvVjUT/jWgonaTt6NTkau3YlLffDYuLU2mxwyZafk/Ruu5w5XCfhd8VYojSbWIYI2V7RhApLTdmjeGQVmxeZNuHJfEOs2NrELGf4pTq55mpHVNKBKDdI3wHOZXUCXRJQoN/2LkJn/mc5bx5BXIVJQ==,iv:P5iK6MhcH6cQSr6lOuExC5EVcxFXv4UyGrMHgJ/DpWM=,tag:sGRJbmEuOi2FItqj4w+1uA==,type:str]
        server: ENC[AES256_GCM,data:7mORRUB90u8q1hK3zwg78M7WQvgOvaQuuPVhLQqjlKDcot28LM7pKKx/X85CwCLuahI1XX1B5fOiJvWghg5/7arWYg==,iv:6O1MxU8p0pDdIaNqPFU2ptOOgooIjHYusPuJyZ+BcCs=,tag:JKO/CYmAPgVClm3Mc7kMBQ==,type:str]
    name: ENC[AES256_GCM,data:7xzE0e0wffoTB1YVZw==,iv:R2htQp2b6altIl0wlL534e+Bq37UjHqsKftkqdSH9m4=,tag:jZ7fn+axYFyxIZC3pH4f+A==,type:str]
contexts:
-   context:
        cluster: ENC[AES256_GCM,data:abR+qHImJLAdAVMchA==,iv:pV9tMndKxF/ewzVGJ8+mkdoY9Dwb6848rhwjV9T2j6I=,tag:ilI4KgRtjb2EESbBKH4Myw==,type:str]
        user: ENC[AES256_GCM,data:Zcysrpu+NfER7ADT8iIpAoI7XQ==,iv:t+me+OQCfocK3Jo52S21GJee2VCcSm3kyzyqWPEu6iA=,tag:ovEUylHPUO/9/KaRvnTE+g==,type:str]
    name: ENC[AES256_GCM,data:U9jzqPjZpT6/swCWDA==,iv:LRCkCDX1AxlO9e4Har57ydxyBdcETK36HuR0s0PQzDU=,tag:/xu4FvA5NXB3ouuT3Dtguw==,type:str]
current-context: ENC[AES256_GCM,data:HmheEh1s1kZkd8paeg==,iv:ynk7HhDvsqjZG5dfldBo8K1ONKAqYQXP/wlQd+hYpI0=,tag:mUHa2XiYPoFl22un1Q65GQ==,type:str]
kind: ENC[AES256_GCM,data:Ib3LUrde,iv:+eUnbwQs73pQ9Oe8jy7Q/ZO3/32k4Vt3mu1aGbXYb/E=,tag:Fva2mNgSaLURyr9uDltJAQ==,type:str]
preferences: {}
users:
-   name: ENC[AES256_GCM,data:+AnSLwOlECDX4DyKpdXS0WA0Hg==,iv:PYaujJiSuOpNjk1v6LxlUy/4zpmjyrBP8VsYtpRyts8=,tag:pCrenWj33aFZuu580WAQgg==,type:str]
    user:
        token: ENC[AES256_GCM,data:UtY6IWFg6oM2B+fcpUbyl5BQxYjYkA0D1FIQoV6v7qmLu9vxtnur7XHp5QSU58RqgFf9wHiN2r1gXJ+ch099jw==,iv:jdfwI22KJZg1C7sSiy9cofLk0QuPPQ9tVal08Pzjd7I=,tag:8bNoDUgvr1gM3fPEul69WA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-11-19T14:42:59Z'
    mac: ENC[AES256_GCM,data:s2dtdi2n5BnT81wdrA3oNmpYMD+zFgWl5to3xWnaX6Xq1d4KCv76iBbOnKvoc8c2UeUKtvwRjnoyvkI5+mQFeeD4Txjn0GBmnM4jJOKKvrMFZ1OFsCz3hl1VOcBlaugI3nsba0r6XDzL0ZfOj0YLNxXJWev2T9Nl/mpBuCZ9AJY=,iv:49UU0QfMqXOKNEEE0eNwGT0qoM2iuVEbEEq0XltRw3Y=,tag:s9RWlZTSjKSdLUocYBMkEw==,type:str]
    pgp:
    -   created_at: '2019-11-19T14:42:58Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6yRV+ftA5XNAQ/+KH6xSiYnacgge0bviUFiAXarCd2uYbg3VD6ACGkChQ2w
            ksFArig/a+04SfW1YQfbGtxZjFR+FOiorM7f7E4ZP5NlfQzD6/1q9Awhq7S+VwwS
            ca8cBoHgO5NC3EE5pWxfzqFNwaxeqdUFbHbbvMcDaU5O0LrE/vDz8y4v3wmcwQZW
            Ic1TkS5RwhjLAmTiupDAZCFJDAyUnrahd/fL+vwVy4egiDy9y/Y2Vk3h5wrJUJPU
            1vTcCMbh7Z2389m32XedDM1AHXeWIqCuEV4pfRG4uZGHV9YaFtPpqgsTioDLJ1HD
            9Jy3v7GNAuPTw9xuAjfOiJm94RegIvDrfT1KbnFRSu6Fr4F/XXSMY1o75oOrP4mA
            SPtFDZqYg+0XFSyq7Sljs0c8+rirhePm6jyt9g0J9lCUj3Sf/QAx1T0uREUf4fEB
            be0mtCXsBxDY5cg+gc+PGeFcsYrQT261rdmYwJXoWmOoI3aN0+ZJW2Q4AqmoJDEO
            yLW0LAi5AwnYxWVWRAbAsHX3GAPdCA29c2JzpQzjoW7KwB+pBJu1MUvBEhYADOGE
            wt9SvWl1nGyvgWrMJCX+zvoKHD+IMb10vRUjtXezdAyOu9vIR8ndl3Rgis7a/7H+
            R/aOcaxzG71E03yj3sslx5U5QytBC6afE6UiHfeSvVseeNVJHJYPP2QKpN8xCaXS
            XgEjiyJhuOLW4i1lcAZ2OWhWb+b9MpKkQAKkAPAJjVcrQEU1FHkhMTdwcY1s4vvh
            tJUpiREBDtgRoC/DVwBXj+BaWfrQxuy7JpGpO+cg3PaEANcGA4gdj4/0XY3X3hs=
            =1Xfd
            -----END PGP MESSAGE-----
        fp: fea55c7794732f67c619951fd178ef6721556cb9
    -   created_at: '2019-11-19T14:42:58Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyiIzYC95gBGAQ/9EN7v12icfBmEUiegAIt5/Gx/J9NImgcNDHnzAZnO1DT0
            +MDwCZmqPapXotNith1Yuh8X3XJtD5Ok+aNud73A1Tb+hSEXkF4zEfw6ZFnZdIIY
            YamukxO7G1o+uWZ+7xqR/Jr+K5SemPGYUE9/3GV8aOxSTyqSqo74qVekK2qttNyL
            xCHlSAGcRKv8PckuwM+QJ1mmPJWooYK2QvzPRsIHwbr+5L9n6quq8T8AxTSirY8Y
            JydhdOQbV4pAoUi4euEN+m3q8XWd3yxIUP3uylRnC/q3eq15FiqYdZTUOs1e+FER
            26jvR9bPZvXNX5UUkB4k96DHRixIMGesL7/edwZPODb2FfHo9LcjNZMVDZvk1zjD
            gm+IZB+EkMhBXsxpegV+T5qvm9aFwqUQRLhgtu8RtQFarjKzWtJmSS/rrkZFmjPT
            iNLVCJq1rX0D/tGo5m7yy3uB7LF4xKW9NYR78gnHqrkTgCP+Gr5WQB6ppeXFAZnj
            X8j9ujAd2ZjZY7g6htrWaNJuXTylvVcyk4cVpsALv39lsb8eeNqhmUH/zNf107IR
            WcXtm4mdHzn24aH8ERBddqLNZM8Wr+kUkQlHd0dU9ozO3H+BYEU1KJvUyop0dCNo
            2ljYCgFK0oU3W8TyycPkQ8jmWM6WDIYbPz8LyJjj5GTJJvnoToeWM78iE8z2547S
            UQFmT7H5ZVpCHwMROC7hLVEt1BnD6bITyNVM4nBHXv3sxGLFxLcMvBAV+V95If0E
            GO1QYdtNs4J8QquRqG0PvV5ieguwbBgMbyqtec2kXNdGlg==
            =BXEX
            -----END PGP MESSAGE-----
        fp: BE13F9D526F84552FA528A09D56ADE51E65A1512
    -   created_at: '2019-11-19T14:42:58Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7WWstCwV13VAQ//Ry8pWY9p645e5s/GXD7P/kazcUEZtdilUWMAFflWh2n+
            jvqZn8Ia0st/S7BBQFOzcKgiyvxV9wmFv4XDmpaOm/v5LogCd2hYA43TA2iscltS
            ihbkpecuCtIZxWE9HF625jIFcqVHNwHnwLx/r6TgJv/goUt4UswQCtOdzx+6KsKr
            awMiaQWuyLjVrHDoqoxCCszvhOvvnF1FFx32PmGaw0n4m9b0SlTbCAD8q5SH/6d5
            ddwgmEYCC8V1omTN8eub48QgTCAFuHA04LhiBZNRAj8vlOGcbbchm3uDObGb0jQw
            kojJ1ShgDpWmG7tYEilu1v1ian9hellMEytmXutjhcv8zEHWSr2Xi+7REPOcXyvp
            HluNwcVObxWGV1YsDpWoggFRalnaI8hDePmfY7I80Ziiux+tKzAAOZQT9a7fR8ti
            2khY7kWhcLcHEpqYmpd/6jBr4cP0F98yK+tWqBbbC7tvteFNNUCYrjaWwMTW2R3Q
            McZ+lqGdlXyXOuFnZkby2xAlm5T3MO/AFIVv3qmBBVlfhYkRP8J1dmMdIpxbyQ1h
            Dq/V5AcXJyawW7djhOwGTqjg9tBrBD4f750KAJhECY19B4ezMFbRVhSVgL3wCgxH
            tkT1c5FzQEVsdVKILP7poluQVBV96aOlxTXcxBUHXNEaZhYZdjGYrQik8I1hC33S
            UQFO5jolMUXIGUvzuMh82agv0BwHGlYrhhRvmoUBhgIFn7qBBgbr9HeMuJL28bJ/
            8Vkvj/Lzy6LTuqEuCcgpNklkQZpyuNgphbBtYO2m82oRyA==
            =HmR7
            -----END PGP MESSAGE-----
        fp: AA337512457420FF9A6298D924BAFA429D76E5E1
    unencrypted_suffix: _unencrypted
    version: 3.4.0
