apiVersion: ENC[AES256_GCM,data:g1k=,iv:QEH3Pt3xXBiEEVOh0RLMr6qPJj860ztFF/f1F2U2iJw=,tag:5pqAoBXXn0yOgVxswKjrvQ==,type:str]
clusters:
-   cluster:
        certificate-authority-data: ENC[AES256_GCM,data:J2RprT2KQAd5ISg4SoLhuO+IDiXgQ9a05bH0TN5Ln2yMG6gb1e28Cgf3FewSJKo5ouyPWuMYanVlcdMir///pHVglpGGI6Cyzo884/oN2EimJY4fLHis1jJoglE4W0zdfEp0j7qMWk+1mZgEvy1+ftvGDfwKHlI7S3FveiEFMcsvIpnVJbmzXwNyEZP61rLaOVk9I6AWQHK1U9NMXp/zJoKG8Y8fomAOeijlAo88Th6AX6Jtrg4Iu0bAm9SsfMmsl51pL6FQtEsiYFmVWDnnZuscGi8p8YXcx6TOkw66bh83JfU3Adw7tm+S3VWSSCLpuU0Lljh+ZymDQnb0ZCNfYBqT3u1gAaX1Bor4UPFDvGOBSWhrhGpUx7aMep9eW2qvI39H2z9RI2XmAEr0IZQE2NQDYSAPP8FsqH/lGdki0AnmwWiy0Qq+sxt75Q+OcHOsqnXAc/JbDb/lWHyGD/yv0zkF+VanGtghFFv1uS/hRRZomOCbOKMmXxu5R9JqnFlhPumP/Q3ZeP5I/xXifO0EVHpfan6zmVd4DorHLaF+iG3o7fZi9DJR3N51350FzwFnDHNUsRw7npd6AvtRiJATi8IYhB2ePAKek6hXVW7eHo7o8YyxVYa/8KhAtRc/L2/qU2M4wdwGrugueGcrRb2A96RW1MZqZYfmAi5qyRPZbxu6bfgK051mmlpWwtSyN21BVX3/7sBeLwzsRRq8Y4BCZWSQDODjTjhHpxERDsyEjf6EyIG32eQa2bFuZFny4BMUxRDX9gkS468dSQyzkkZZFniYDXg+GZsBJxDb0jdMxp7T4U1y5TzCkVfCjJPgxr08aGg8e8gRAcrvE3OIgu2Ex+Exon8qQVDyOwGl6kR/2cr/jWJnKEcU9mMXVwBsqRYkrJk6ocoxwvTxDwE3J4vABTWuT8IrZ3XlCz+y7qkzjBbZELjg/UC75yI47UWPc4vPvNF3qG23bKkt3ywi2fSbW/mTqXv1NePvcBLT3mDQbob3TKAkXMHgWJG0SAa28rvCxkCLrENIMp0PdLMJov/LRpvlyomQhA9jj7BS8WB1P40aOdZvI6i7JELukIJMwIkxV6hHwH+pcQ/nHINgWEzYkmylG7yUOuNcpq5eoi2yPH/2aSJwD/IAohFVsGe0SgJLMKvhl5LuytoppV6fFHba/bkkYhkmUxLIWQTRR29pI6JT7/rrsnqmvWpqFOEeuBKbqPTL8a1PkjMFq4ws4PtuODuuKXGJ3RRu6HtY5QFMXyRwo3aS78AI3mUSJ80+hgoQsnsdcMMNigsFferrU5zd7n/fRrjcSbn62g0jNVW5QBkdMGoGE595x5fS3XsBuaXX2sd6bUMgOkYrQAxNbhG6Sb5E/PIiqRgtSJSZ+bF8t2QwiOcjLm1OOlbUHYGkPjN3Pj0avFcOMwLgQaBMLxsi51iBogXwY/gOYHzqZLjGwHUBRU9TBWDnH7dZy76XUeaI+O8B3I0Dy5ZIiohEqZb+Jd+uz6AA6cxM9DYiIG+uVeQjq5hTT2PtrgEHKIWFiLs6PZ/x8MGul2fNw8gkJ6X+ADEKFDnnjX6MNmL71duXxonmj0a/rXxfsHrdnPgoQJHZEeY/DAvceQ24H9k+uYutqxMOTNbghU2ianvwri4/BJrMgOyBr3lUbGhFJ3R95+tsTrqIxK830JRPsbxCFCQUzIfruV31H1me+iWvNw3ceBACeiduxrRz20ECgsFCNA4SnDrsIHUlGOC3/novt1UcqWkyjCkjVGPAnky9FaAbwmkM4uUwY/LIyOpkAVDMHhQFMn/6aB4Birz4zX78VvzWe0FSMtXLFRyv/APwYCRCbn2DtZ5tj0l5ibDSvBMwhGPt1n/AwaDGX2cYfLlGJgwolCSecgrLePynjxlPwt27vyGPV717E2PLYTLY3Vdk8qHbUsARxQdVJsDjPY1JsDNiXeo6tUnLFV7aJZr72e31sx0q/Tyc5PuKD5elOaRYL/64qO3w5IBydjWe3OcL6P35FUPUAQg6/hHHz1ySNiEdx9BqZKLHBWrBeDUZBwabvmdc3Qj5jw==,iv:LnHbaQDGrM96ESf59QS0SuG/zxnpgzH5nAm1ejswK0c=,tag:zTX45LaynULeJ4dydPxn7g==,type:str]
        server: ENC[AES256_GCM,data:YVtQ3d0PULO0zfzuo54geAlht07IUFmKPA5pAu67bBP2sHyajSPOukDT6bbzoaOTy8McIg5YIrdQufNixAORHGtxhQ==,iv:kBrrCfEHxitCNaun8Po/OmS3TfZYzVqgLI17JSr3vfE=,tag:yVXwqB44RYiGM7sk/6rkCQ==,type:str]
    name: ENC[AES256_GCM,data:bi/snUTI3acgQlfW1Q==,iv:R6nVgVyBlkF5wd8OnciTxYhmpy7nbAZ7u7OphsRRpUI=,tag:JQyOD8OVxIwHaHcyfuIDbA==,type:str]
contexts:
-   context:
        cluster: ENC[AES256_GCM,data:yIZ9iA4KtLk1n2pMcw==,iv:Y+fovDWKjLFGP+k2qfQLDho94RwqnrHKoLpmfbDJ8YY=,tag:zo1cIOMG9utTdcwMYhxHlQ==,type:str]
        user: ENC[AES256_GCM,data:KCtx3Aa1LyHRbLsUYwzDXZNH/Q==,iv:XWf1P4FPYQbITqberINjZFb0a3cOVl0hgbq474Vk7V8=,tag:8rPY4KNYwukRg0WIjGPMSA==,type:str]
    name: ENC[AES256_GCM,data:pUoOBH0izbuTiHb4tg==,iv:SwpNJMZ05Lqvm+f8DLoNLwDJjSosMQBEuldpMxdvIkU=,tag:UyPeBqqF81uwNtDFRB9T1g==,type:str]
current-context: ENC[AES256_GCM,data:+RDfE8UTci22CDS+UA==,iv:Oghioo6A+7nBUxifCa9A5xqaUv8InqlBVGa+FRlNxEQ=,tag:2FPg/wbeAcz6zONglqxfCQ==,type:str]
kind: ENC[AES256_GCM,data:8uk8rSla,iv:TSkpkjCbuQnzjB/LuJxb59fMg4vllqS0huuIU7tzLP8=,tag:7FXDDWibE33ZB9ObItr/wg==,type:str]
preferences: {}
users:
-   name: ENC[AES256_GCM,data:+BDQ9DsEwg1CL3awrkSpCajYgA==,iv:2E07qFx+Yxevz+jhavpvsyV4/Goehe9zDFoik9DUbYw=,tag:tsdOXyMnNAOHGj3zQDnwwg==,type:str]
    user:
        token: ENC[AES256_GCM,data:o8uMvcttzy11UUe5T9trfSr4KNZdSDKhY6NH+LFnE/TqkB3v9aDPf1P4VXtb1VvgB2p4UeJXdp0HXIcVb/ox4A==,iv:w1yW+YYdyFzvc4U9ks0X52jHB1OsxWjBmfjRED1vWP0=,tag:LsZ3E2Ho0dw4wYRHvu9WNA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2019-11-19T13:46:22Z'
    mac: ENC[AES256_GCM,data:4Hm/+CLlAotMOMui/brh/4bsDyUtq221QksyysznomWWDlAaVuuwKkcifRCSVk8+3qW/Oho7ht2My9hCghAiZMhkWdxIAoMMwWLiVRPus893SWRvIfk4Jh5bxo6jeAEvL+KVuFF1RhYy+2Dag38mPl+5RvpoJcvP2c+yTgvoG/c=,iv:9lsqTX9COirhnZK8hP7i9HJSteglewUd2/+6xuzFQs0=,tag:rGzKAawxju5OvvEM+hvQqQ==,type:str]
    pgp:
    -   created_at: '2019-11-19T13:46:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6yRV+ftA5XNARAAh3i8g/IPR15wrAYek2TUwmo3aq8PVTtqw18zBAg02/VD
            0itJ2a+CuxqyV17N0IiPk1qwFzudD9stWtYuTH5EiKeHRrLHviffiwKRlNrGID3B
            d2D20eCHEOP4yiYkbGNa8uSquvZXVtwQMyux5jX+p2ms2OYYAjemXjGwoEBVMP24
            cRNL72Q2varSrUk/hHQcOSK5jb1ZME0+497WS1qugX/jklKIAYi1FdJzGkgXIqlA
            ZU0rIvUcjA5IfcoTJJ3cSgWNw8PHYfuGKS/poe3WdUMARvfSX4Ig9Mni75p3vcOb
            6wMCcV/3n0Kycezg7ng/HFbYJkokVzUkm2GyA9dGehHeFCZUy4rGZ2B0KveN6OY4
            UAUyCBJ2Uvxh+kX3MCnr5UtuV04HzLyN/Fsx0TJ68FBb0SoQTzkbQ1NfpyHEpxw+
            B1Dt2pLPjD/pB37C4gR/jPtV1W7zqisYOcFbZLNBNdrMx88vMVRUixFp+LqGJA11
            NA1MBceOo5cJrADcZD5D6s4H4dcY9mJKj0U9oF8crOshOlsFYLRLnZytGD+y1m/U
            EQy7c/9O3u94SxQbq/PHmVuRxdX83lH0Dqc0673X/UbyYErmK/UvyckWTxe8OccB
            TyQ/B6aeAcn/uGLiJLWgUEjfth/HBiESdzWVHE6yBS4olvjPDFeEhHV3CYuUjAXS
            XgEyZR65ZfCuOBBiT2OX7zrz5zdn8PiOkDC8L+0x5sUpPo+6q3zTyrpBsS3VXXbo
            TflD+HMYvvsQhYnK/ID6OHFdifV0mvWVxyUCmR2AyoMUd2zoOV+/Y2uHK7B/UVw=
            =b+f+
            -----END PGP MESSAGE-----
        fp: fea55c7794732f67c619951fd178ef6721556cb9
    -   created_at: '2019-11-19T13:46:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMAyiIzYC95gBGAQ//Wy2pDKmyU1MGZNXliSYZToE8WO6sY5yU5kzBGD+PpxZg
            NGYz5xIXKZzvRB607ctv/5FH0NvME9Zo9ifh4pIp1geXZFBLMSeipjhwfwYluDLB
            1YsXQP/Sl/Ii7gnDjCB3voA9e+GJpshAEE9zui2Yf/Hdd8UmQueOngLw1dCkJgu3
            o7iLmTdwgHL3c/nMkH9qfg2z5C2tcrxF15zF5RBe7LMCfGldn0s8WahDBRDYIRzR
            lwscmDDCGgVk9iqgFMfIXAAKKLyZF4qlB6NmvfgAbuBhIqjRlN4O5jwJ8TQkWvwp
            LJx1AuAnMLbmEg7UBhXRf5gciTAK/dIxPOggsrDZvf/GundtWJYM0aXWcYHwciMT
            MsHCRr52U67yY+F3nAExu5kTzt01hLqwvnhUJflFqxPzJm+lUT73Z4C8hbZMBKTy
            /jT/VISR2rl7n2LcFCg3eVrkAoGivNOTp5y+7FWz2H4Bjto0wa+UOMCFNaNs2g/4
            HjJ7IFY3UEymazj+gh0Zf2DABevR//7ZPKSU2/jIQQpWSR+Zx+UjIpon/ESUGziN
            9bTRY+bnQmsvJDCAFuhPBhYOdTc1a9P1LVkIuTVBch+HQ9eTQ0mceAIWgMZ08nE8
            uZ2DTNqoPWjJb0GtwMhlwnxcW0zAET9HdqHzLIWswscRNYRnthR55/1X7bmeWC3S
            UQGXH642MF8Ov4vf4CxmrjynlBPnGJ0d+gNpGyjeAekXf9A/Uer9I6WwBC4y+I6f
            x35GZXSRF1UxkAgFR89SDH+YOBDEZHmmStXjdfluhRprNg==
            =r0eO
            -----END PGP MESSAGE-----
        fp: BE13F9D526F84552FA528A09D56ADE51E65A1512
    -   created_at: '2019-11-19T13:46:20Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7WWstCwV13VAQ//d1HMXyFM+NywloUN6XXaJHuBDVAf5SUrQFdJ09uAGfT+
            /rmfVJrsiG4//Eyf/b7q5/xn6QcA3xDlTFxlvz5wMtt7kUChJoFcURF7loPIb8M8
            tdM2LPD6+AD5ILDF0TjIiKlMQIkdvsZ4VlCQoVJc3df3jrzH3VpqRE6KqeoZo19v
            dQv3llcFm4aq4wCdeBVKoPeXXadFncjRUx3N+MVZseu4QMX8pUUuJhfTXTs9sTJ3
            LrTW3inocYsmJlV7qjbQBpHQN7r0adRZ/G+Jbo6GJy79gLHb1L+savX8BPyfg/gH
            F9D8bqZ4pHMbj987SDFDK1uBCkSG48EWsKxoJosh7BQtLXapOv+h2jFCuIMYUf5W
            xXTxBovRPwNK7hkHYaXUyFbj/HzDPQo/HQbnFXeZnqTIVCgbQoVLaDAnUutpPvgs
            HdwvZ7C0oNqKB0iuKnUQyYbObhj0s1j+y3hfw/Mv+LQw5lyvJ2ZmAkE5oC0gCiK0
            Ny67uGpsPW3Z5lUHIjbyY76+xfxqiVgN4tG0zN5mQ7AiNhXpeAn0w6e/9c0eAoHe
            welMIYZdSjCSceDHUy6JLH1vWIEeonaBu8W3r5kkqRl8DPdR5AhMS1pv4Gf5+NM1
            zmHWR2ikbmPettIRcSSCN20h2u2DE7SRqnPSzJjWjkBgnm7zWfcQ4I9o9OH2yUXS
            UQGjYsm/LaS7DZ1BnX5ZxY+GfO09qbk5rfeNIJZaEUHViie4OXth5iXa631Q4oQb
            6QzzZthaxGCRiNHZWjotG9ptBhGia+G+IvmpVmdnjCsu7w==
            =9oe/
            -----END PGP MESSAGE-----
        fp: AA337512457420FF9A6298D924BAFA429D76E5E1
    unencrypted_suffix: _unencrypted
    version: 3.4.0
