apiVersion: ENC[AES256_GCM,data:0JI=,iv:mLXwc8AFF1YBJYuo0HDwumLYmusrbzAGRqArgQusVNs=,tag:gjm7yl9ZoetOPnUPgpDQog==,type:str]
kind: ENC[AES256_GCM,data:M2vfolTi,iv:XopyXPJZZBw2/nGGORW+dnE6+S1YojUor7iHURBtGNw=,tag:js9mVdx/dM+TC2ZS3Lcz3w==,type:str]
metadata:
    name: ENC[AES256_GCM,data:rynC0LovaA==,iv:wvdUz5Ds9AJdqzxzojdrMbNh6955APDsHAmyKZqQVy8=,tag:AlyR54pHI0iNXg/Lj/IAzg==,type:str]
    namespace: ENC[AES256_GCM,data:3h4kyR4rPBrZ,iv:F6qDBOxItoVURxRxiAxmWnlhgnv+l46WLkevD4U+5J0=,tag:vkQzXg6mCeMSYME2E92EFQ==,type:str]
    labels:
        app: ENC[AES256_GCM,data:rPpqivuBLw==,iv:2cxRv54IFRKzttsYf8ZGkb3+arSZJEu/5A6Zn00Jb8M=,tag:RkUyksAxlZZ76KJN8l0jxg==,type:str]
        chart: ENC[AES256_GCM,data:icZZH8t2BF2yJ7uyEQ==,iv:HG0HvUvwhD+I3e2tjcQ88ELJS5zlRsItsdIiEmOBLsw=,tag:hNuI2ZBJaEyj5XCi8jrDMw==,type:str]
        release: ENC[AES256_GCM,data:a8LfMx8=,iv:cn9RsvepIDrig/+c5y95maUgKASl+qqYUKT4AmzdxAo=,tag:T6nTPhi4zUwvQO7hISUJqQ==,type:str]
        heritage: ENC[AES256_GCM,data:HFdmOg==,iv:R7xSAPEmEeVQ9bR973VcIsq7Oae2+a2+3S3NEfBRnAM=,tag:CC0nDmxwFP8z2j9Gqz1p1g==,type:str]
type: ENC[AES256_GCM,data:4zogKWBv,iv:Gx8pXUDteJFf1V43SbJPLw6RLaDrFNwUknXGsD1XkFA=,tag:dIUbi12dbGbJFqKgfkeHhg==,type:str]
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:zVPRLjJWew74tl0Sex787Kn0N+Gz9RdL,iv:mZWsEaIsD9oC+YsBTsSYJZns0gRbkfQvqM4k4wJ8Als=,tag:KONU1Hr16JzceSp8WENnEA==,type:str]
    mariadb-username: ENC[AES256_GCM,data:ajdBy0YhhvdoJYot,iv:llHcCBaULH+7clQ2ZpHkgUNUxhpKp/hogqO6AywCRDk=,tag:AoSgnpOsKioWzVidpCuANA==,type:str]
    mariadb-password: ENC[AES256_GCM,data:15rWZYLMnGi0atNPNMzGNS1NqjzYy5vz,iv:DvjnxBfwAYhCKuqqyZ1W8IvJRh5XpMVx4AXyZwz8OTg=,tag:9wvYuEbAMOiL8b6UKBrmXQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-01-27T14:07:20Z'
    mac: ENC[AES256_GCM,data:fLVIG0X/Mb0KkhvGQoQ3dBZMaH+SwK3gafk4uyGyoxoxTMjGFgI8fBNUbjC7CMlrfcEy6+2y4n9w7RZkB17K8A48xxJsE/ZCx+sfom2idConl9SV0qSfU+ayPOThPkVeNXEPNeCw9tCn69c35SPhXxuNhsFq0zMYxTm4YVPEuJw=,iv:FlgcMXGItW6DGTZrWGLOo14Sks1lnlnvG8ZS7bZtH2s=,tag:m15PZnts3Y1jGvCs++gsSw==,type:str]
    pgp:
    -   created_at: '2020-01-27T14:07:19Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6yRV+ftA5XNAQ//b7LyvcwUsTdUz/3j6X2n8eiEXoU0Uuj+37mCGGQVoXiD
            8xOSToHep3QAMM7S9f0g418DiRHl3Cox0llbv7nCHNSzE8kFcF2CourGk2xyOuVA
            AHD+DIqFx8iQzpfHgc8a6ITRmfKcE8OeIkzYmmJ0L15H5klMGSGyoX6AMhIF3d1C
            26KnT9XB+OMaCytEwSr7QR1iWVbXRvLsPrh5yk6NQF9Vylv63dgjbPhYBAhOSSSl
            yUZSUCkdyn8PqrO/UKPIBB5NUvp87WP9irjdw/Qb/DodlCYhrcQ92BaIz+exQOuu
            yH3wY9v7jawLhjIy8rZbODSk6kBoezYDgG2zaB9TgzuVWPchr4dKiKN5ZzGYQRGD
            cFt2aOxl7RQ/w0uNGXK0FfU9ucMcxiU+MEDd8eXVKeCKLOILKaXGOKA2ysdEcU1L
            XQb1XbwWnIkh3Hk9B7GI+P+UN6hHrkHAcO+f/03ReFCA8mQLgpbtXBDGB1CQIXEF
            LBdy8IQ2GtHdtVSlN8lShmCPoZoSCJ9iVJDNWjBA1oy6EnEBxaz2YvV72+CwZZkF
            vp2wlqaHKSUMMazDO2pgV9xo7Fuyf1qgCEPE+8blMaqI7JO0peEo+oz7YTMEbB2m
            gI3ar3IDQX83KMLhdqguU2I1wh5Eatdes1L6uvZjUUu0+S0gjXgT/Q17+/GbQCrS
            XgGpbhh5arSyG+ZPYmj4119VxihyEhPjtyjajcib20Ye+r/X/IHgptzKsY8UqMJK
            fayvINotjHFPqGbZzemxSRFLttaDtvrs3vdAsXpQyd+H6n2l4lvKQ43yQxcvE2o=
            =eUKW
            -----END PGP MESSAGE-----
        fp: fea55c7794732f67c619951fd178ef6721556cb9
    -   created_at: '2020-01-27T14:07:19Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7WWstCwV13VAQ/+PZbXfb65y5lwsJh+G4YcBKJCnQcBqM4pmgKNURFohvuk
            LYSJ9luinomjrmepauwszT0rQtPW2vSvwG2R9DxIn5Enf/oZRaDzuGsuzaCdiTT1
            VnVDhenQlttb0CpdSMVTle05ggQgReGtbtt6S+xtjheong+gqTO9viCyY3qMa91E
            7Jxd5V/wHNS+8GeFvwQWgIBnIQI/UVhB/bA4C8VQzEZRYccZZMl+SdBTxwVdx5pt
            xfxERZOPfcJJeM8VyB9gc3j5Qmn401p9ZcgItapDK6qaL/iyPPVf0bNEkbF2ro4M
            YagpeJ9QsgzmY8qkA1JDzreLmsFRI53CAW9nNsj4cBBDbFkQ3DIy9Q+9aAEvgdY1
            Da+CHJksjtNQNG2uE2Ze47k8s1mGIltPvI/VkWiGoxQjMkmiPzs24U2apLbOIQ0M
            9z62lcMrDFHLS5QzJIRArVMNbF24nCsXqQpZ8+rJKb5pQUnViMXCVcbIEY9gmZgj
            digkXGflDcBUnHUgk/7fjH79QacpZg5P4iY5sbeatZIJvdd1IoPqYKKVRzLeVFRl
            KYw8jF5zQ20cZxE8vm91aH0oPACg8OcCbppAb89cl6V04wH5E9EBbkjmY/3ZPgeu
            SziRhn/Fr01eJRWD1r6f18H/0A+dAz9KGIos7YbZvKruc7khYMEaQMitLnz+StvS
            UQH8P+3FbewmOaoQt2KFVbJE5l4dn4oju/Id5hkbjw7ug3Iyds64///92d7D+8Jo
            JPV86ToQ/oOEBJPb1kTVeMDdNZ2vAD6rJEkTV/1CGSpYvg==
            =/D5g
            -----END PGP MESSAGE-----
        fp: AA337512457420FF9A6298D924BAFA429D76E5E1
    -   created_at: '2020-01-27T14:07:19Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMA9UmI4H80NG+AQgArjZ7zmMyVhBmuHXKn/j9QWnR2F4ad3lRFVu+XFCLTE8a
            /g1YcPgUH8r/6/2AXjw4xGPc2Nz8vVRyquj1pzDdKDReWsTDEDSxDtOWaHKlP57r
            WYLNuTQ4J856ISgUZfgOG+PdYORaX+ZKcFg1wERNwiSnxGDmSaOWGhmQYBD5N345
            9oSqngf1sxxn4ehSXLMnssmdT7TVst1x80AWgO/49l/L6lR9+Gil1zljJ/qOcQ8z
            xK4K5Vsda1p79a0g3h5VnUEh/e7cYiswZ2CK32F+VaBcBrM+A5ubgAuynFR0YJmt
            POeRxbpszg/sZ778ArpBjZ5ZlCcTroF7HWnvR8ROt9LgAeSEek3lkJNjmivRg15E
            yBp34Sk64PngtOGqSeCR4mAiwxjg7uU8z65jETNOnTlOxjPQHUyC2jaDhsL2I43f
            5HaW7xqnGOA75LiFqnZQQTMXzLL8G1raG4LiOgOtPeExUQA=
            =LT4K
            -----END PGP MESSAGE-----
        fp: 9dbd5bfb2f45e6f6c9d7b3997e377e15398cc61b
    unencrypted_suffix: _unencrypted
    version: 3.5.0
