apiVersion: ENC[AES256_GCM,data:kGQ=,iv:W3DWyncSjENzcLt88oMtvsd5TtBJHKtzWnPmj9DjqZo=,tag:BM1OSYxdTPp1ClmUTByw+g==,type:str]
kind: ENC[AES256_GCM,data:TDZonuX3,iv:xh7THJxzW39GSyKTVj3a6XHwe+q+6fIUk2adhGWd3lg=,tag:EXPyR1a/5f9NkgS/M3kcog==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dRrarzMF7g==,iv:Y5Teab21yH+g2wMTx0pZbdp04FShEeDfYjjJjFw82cU=,tag:yTuv0yeanvzp3azSBqa+xQ==,type:str]
    namespace: ENC[AES256_GCM,data:ehkwN0S5rrgk,iv:8iI4ymlXTcnGrzK8DiGOjxgM9iJ1qN1Ryn7x+m+krbQ=,tag:A0hiKK8jxtMPdyMQLa1G/A==,type:str]
    labels:
        app: ENC[AES256_GCM,data:6B4H92A56A==,iv:pYfz+/dVAczqyFDWSivBuXSJMK1BILOe1W8mb3WlosI=,tag:la3pdHA6VapfQRzIK1HaXQ==,type:str]
        chart: ENC[AES256_GCM,data:n525mgCyedF1kNIN3A==,iv:9fZcvwfIrR3++HbyoYzZD1hgVTwAxVrMVMVNJNl9rWg=,tag:CMolUeDnmZg4FPHliL5E5A==,type:str]
        release: ENC[AES256_GCM,data:N0WrEYo=,iv:2OR30JeZ/olzDi63c0Pm3z5XBfVURCLNIwaJBbDKLVI=,tag:XMBG1fEsTTTRxJ/DkyxDqQ==,type:str]
        heritage: ENC[AES256_GCM,data:zQQeeQ==,iv:N6W/4zaFSM2DlezrG49o9Kxt/RI4eHzPb9KfQvm+rQM=,tag:U748YfGSETdOtsIBwhkSSw==,type:str]
type: ENC[AES256_GCM,data:QQCrTqGg,iv:ln3omZ4kT2BxTf9ZDkYeCSOpV5S6N9kUgkp3URTn4vA=,tag:hb65AjSUkv9Um08IF/+kJg==,type:str]
stringData:
    mariadb-root-password: ENC[AES256_GCM,data:PsCiKSbVFQjGw9ImqW1FYgHVUpoaYu2s,iv:ivVD1cNqaMSB1oaJADKXuvOgbeP2zO2q0J8bnlN+IGU=,tag:yC0DgksGMfbPAoYd6Fxryg==,type:str]
    mariadb-username: ENC[AES256_GCM,data:hkYO9MH00W6EexBU,iv:DD+WqF1Hwz2tPPJTUDAo5hdnllapEoCFmNsILZT8Ug4=,tag:wNf3pb/d+cEeN8UmckAaMw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:afSu3ky8069DaCNJCZWoqsFFBfdbEGE/,iv:waXAGaIkx7LYWuYENtmNOo/Y4QFiluPj9hgwEyBXnOM=,tag:srsHMCai+YitfTrnX+xCxg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    lastmodified: '2020-01-26T16:29:29Z'
    mac: ENC[AES256_GCM,data:PHvChf+ghVbMuAVAlO9QGAfxFicUACN5IKOYjQOjnQIBRT613sAz+61k68zkAx/MFrwqXNv1p5XM70XbqQu76nK8Q58AmHwp69xVpXxcp33HEJnJw9dwIHdaOcexBHnntisxa/pyXf8luQjSULlDjeFMNILYSHWcttTVBHqT6aM=,iv:lhtu34hA944LvfwUxLGXxgfgYGYq6KOcG44YYn9DDtg=,tag:OYpP3l9eHY2X12551XtOCg==,type:str]
    pgp:
    -   created_at: '2020-01-26T16:29:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA6yRV+ftA5XNAQ/8CNHWPcWBoo7w7NAR9r2ob2TL2CZ50phDkIeO7gDhJWrV
            RK1AVfT+rsqoGp8YCHcoGcneAmOKTweSGM7pzxUJkGrquQ1I6+NwnZQSsMB42gGp
            NqSKYQJufIJCFMT2XZWZn5yyVo/U6ilqdY/JTaVnF9a69pcNFO0VFeyF0o1wW3wa
            myUl8heJNFP7WA7hgtZuNd4Xaz5614uS7CasUdDSBIUzA2vwq6C3FTddkblk4mwC
            7xs6Wg6ToIMfguLhpAeSlTELsfzWwk0jwPNLNCmaQJ82apzODh1S+M+JiHoOLKAd
            GNiDSvmMKNFRpCsG0K9AsgIrvXq9ZyNRP8nuzwoNjbFlDWtNYxRSQr9wjOxtCcTI
            nfQmIGD8bwBDioxn2Z/ZRc+oB/ifbB3oEgFKPn6oJ6uFcx3dfiHu9ZT85KymRbPg
            T6FH0lHuzaGBugf6683YRWJqGlBTE/2HryRazZo32+TYXlr0TRBj0E2RcJ29MzcY
            HY7TLBcvj64Ne/85nW2+6c31Xptu0e/sApvcN8SDwDYorg7D8WapjeQAePZZMCf1
            QZiMpgxwg4yeIWL8LMrwa9JVRc2BNIxFSTIfSWI67uAIASuxVHC5x7Cepm8HSa5u
            jZF7ajfOm5KmTz0s3bjqpl0NIHDnRX2R4bVF/lLrPdmDfCPCcFTVh35m3mv+LnvS
            XgEDe4XaLqjHFqN2t6ubp3OArns4LV24m/ohErPq1AUbC/Mcw/hII1kYXjxSW4Cb
            xZ3kJLrmflCU3g1haeGkbODUTIa62mZ6DQrlmZkJjAWzemVCFsTwt7hbBB/t+q0=
            =Aw4W
            -----END PGP MESSAGE-----
        fp: fea55c7794732f67c619951fd178ef6721556cb9
    -   created_at: '2020-01-26T16:29:27Z'
        enc: |
            -----BEGIN PGP MESSAGE-----

            hQIMA7WWstCwV13VAQ//Yofre29pAhDWXumQStFrc+2C0g2DOYlc4bu03tXO/Zyq
            sqxXQGsRUcIWF6YvNIVdOAiPj1BgNIdUL3vaAFDBy8Of176aWGlUGtSBa6IVcjPH
            nhHHyR0d5CzfBX6sFqZY4/erpK7L/LTuvcSZfMhd2nSa/xyXslx4QVD4Q1GefnVC
            fl45bxnT6RB0WGxcoeUnoS68FQ0O9FxapN5wnzHqqGfliHxQcTXEvx2yuqn0i904
            skrdL8Svw/CHIvTW2LaoBhLVqkzhXc1xrRifUPz0DEBCeqa/4i4I1K+InvQVbYH0
            nDrzmISwZDtBmpn/6JSiLivs3NxQ2XWexctcTALLMN0hlnxmjzNPimEKOwb/3rVB
            /8sQISzxOSkc/paqTQ4IhKwkznrYN4BcjeJqDFuth0Mz0AkQJThF4EeXFrHNJXIb
            FXydLC7y/NaWbm53dQWK2EYJks5IS9s/zqgs310OWjG2l3FW8QzHYeMgdjgcqnLJ
            UKGdLZoeqHivCmkHXNU8r3eP3N0EgRJZB+kwO6VBOlHpsn2mCwksBApWbunX4xNP
            BtvzztwNWGcw940Uc/LQ7Ui8BbBCo7AP2ysQBNipcvlyIdyv7oq2MMhwxOf1E59C
            ziNp7pH3ioOvWmZUElfmgwrD1UZDiZnW64xm2AHKMTlpJ0PbrNdzeoji7s5Izn/S
            UQHzVrc3ecSn71CchX5vdVaIFBX8m4dw2qtkOiLB8F6oxM+gklc9QeBGTlEVDtFJ
            MATuOvPo0xZzAfR7LIcXVdBrukuaAbxfBXN2pF/EXjf+fg==
            =yERh
            -----END PGP MESSAGE-----
        fp: AA337512457420FF9A6298D924BAFA429D76E5E1
    -   created_at: '2020-01-26T16:29:27Z'
        enc: |-
            -----BEGIN PGP MESSAGE-----

            wcBMA9UmI4H80NG+AQgASZRZawzxxiq5sBfcYvokX6YZe6YsfBFEvWML7WRRhuEO
            n3wBXc/L0sCNabgYCzey6u0j3zPvblY/al8rh3JHij0ZdpLFDztVdx2g4afpfXY+
            lj801pxUbvj/85gGkLpaIwJUeS5/38firqJPFKpjT3Ci5Tll+7nuCMoOAgCwv4K0
            riKSVTpsYJ2X6nnTP/oI4TrBxoaeu6Q5IHZqgPrUozJ8SciDygugAbaKF4CTFzkJ
            JuUfRBMYTDg3P1UjDmh5obxKcUWUafcyHHM90ZjBkIWyahj7/G0kS4HK6ND2ZQKH
            2oOz6hZIUs5lyJkkHL9vJYwrkFQDrH0acNWRP/Fn6tLgAeS3A2zgvQScq1NR5VmQ
            gphS4Q2c4EXgF+GrueAv4iECulXgTuUlbHucIYXU/oW6pozVF4OB8Seqq8OMriC3
            H9j22deYv+DJ5Dp80xX5aE+w4tqwstkx7sri/VjIueHEwwA=
            =U0Hm
            -----END PGP MESSAGE-----
        fp: 9dbd5bfb2f45e6f6c9d7b3997e377e15398cc61b
    unencrypted_suffix: _unencrypted
    version: 3.5.0
