apiVersion: v1
kind: Namespace
metadata:
  name: kube-system
  labels:
    name: kube-system
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-limit
  namespace: kube-system
spec:
  hard:
    pods: "30"
