apiVersion: v1
kind: Namespace
metadata:
  name: rook-nfs
  labels:
    name: rook-nfs
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-limit
  namespace: rook-nfs
spec:
  hard:
    pods: "30"
