apiVersion: v1
kind: Namespace
metadata:
  name: rook-nfs-system
  labels:
    name: rook-nfs-system
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: pod-limit
  namespace: rook-nfs-system
spec:
  hard:
    pods: "30"
